enabled: true

image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"

persistence:
  enabled: true
  size: 1Gi
